### ISSUE TITLE
Local Echo in Tasks not working as expected

### ISSUE THREAD

**Issue by The1andONLYdave** [dprandzioch/avocado#18]
Following Code from example Avofile dont echo anything:
	# A basic task definition can look like that:
	#
		task :do_that do
			command "echo 'foo'"
		end

If you redirect into a file it works.

**Comment by dprandzioch** [comment]
dkulsch did you run avo with the `-d` option? This enables stderr and stdout redirects.

**Comment by The1andONLYdave** [comment]
called with -d everything works as expected.
