### ISSUE TITLE
Git tags in deployment logfile

### ISSUE THREAD

**Issue by ackermannd** [dprandzioch/avocado#35]
It would be  nice to have the git tags in the deployment logfile to easier identify when a specific version was deployed. 

Currently you only have the commit hashes in the deployment log and have to search for the corresponding tags yourself. As the git tags are already a cli param, this shouldn't be a big change

**Comment by dprandzioch** [comment]
Added in 0.6.1

**Comment by dstapp** [comment]
0.6.1 is now released as a Gem. Just run `gem update avodeploy`.
